spring: 
  profiles: 
   active: 
    - dev
---   
server: 
  port: 3344
  

spring: 
  profiles: dev  #开发环境
  application: 
      name: microservicecloud-config

eureka: 
  client: 
     service-url: 
      defaultZone: http://server1:5761/eureka/,http://server2:5762/eureka/,http://server3:5763/eureka/
         
---
server: 
  port: 3345 

spring: 
  profiles: test  #测试环境
  application: 
      name: microservicecloud-config
      
eureka: 
  client: 
     service-url: 
      defaultZone: http://server1:5761/eureka/,http://server2:5762/eureka/,http://server3:5763/eureka/